- hosts: ise_servers
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Get ANC policies
      cisco.ise.anc_policy_info:
      register: anc_result

    - name: Print ANC policy
      ansible.builtin.debug:
        var: anc_result

    - name: Create or update ANC policy
      cisco.ise.anc_policy:
        state: present
        name: policy1
        actions: [SHUTDOWN]
      register: anc_update_result

    - name: Print ANC update result
      ansible.builtin.debug:
        var: anc_update_result
