- hosts: ise_servers
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Create endpoint group
      cisco.ise.endpoint_group:
        name: Sony-Device-X
        description: "Identity Group for Profile: Sony-Device-X"
      register: endpoint_group_result

    - name: Print endpoint group
      ansible.builtin.debug:
        var: endpoint_group_result
