---
- hosts: ise_servers
  gather_facts: false
  vars_files:
    - vars.yml
  tasks:

    - name: Get System Certificate by name
      cisco.ise.system_certificate_info:
        hostName: ise
      register: result

    - name: Print result
      ansible.builtin.debug:
        var: result
    
